modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "LGPL-3.0-or-later"

[[mods]]
modId = "controlify_splitscreen"
version = "0.1.0-alpha.2+1.21.5"
displayName = "Controlify (Splitscreen)"
authors = "isXander"
description = '''
The most advanced controller mod for Minecraft.
'''
logoFile = "icon.png"

[["dependencies.controlify_splitscreen"]]
modId = "minecraft"
mandatory = true
versionRange = "1.21.5"
ordering = "NONE"
side = "BOTH"

[["dependencies.controlify_splitscreen"]]
modId = "controlify"
versionRange = "0.1.0-alpha.2+1.21.5"
mandatory = true
ordering = "NONE"
side = "BOTH"
