modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "LGPL-3.0-or-later"

[[mods]]
modId = "controlify"
version = "2.1.1+1.21.5-fabric"
displayName = "Controlify"
authors = "isXander"
description = '''
The most advanced controller mod for Minecraft.
'''
logoFile = "icon.png"

[[dependencies."controlify"]]
modId = "minecraft"
mandatory = true
versionRange = "1.21.5"
ordering = "NONE"
side = "BOTH"

[[dependencies."controlify"]]
modId = "yet_another_config_lib_v3"
mandatory = true
ordering = "NONE"
side = "BOTH"
